// This file was generated by ecm_qt_declare_logging_category(): DO NOT EDIT!

#include "compare-logging.h"

 namespace KItinerary {
Q_LOGGING_CATEGORY(CompareLog, "org.kde.kitinerary.comparator", QtInfoMsg)
} 
