// This file was generated by ecm_qt_declare_logging_category(): DO NOT EDIT!

#ifndef ECM_QLOGGINGCATEGORY_KITINERARY_COMPARELOG_COMPARE_LOGGING_H
#define ECM_QLOGGINGCATEGORY_KITINERARY_COMPARELOG_COMPARE_LOGGING_H

#include <QLoggingCategory>
 namespace KItinerary {
Q_DECLARE_LOGGING_CATEGORY(CompareLog)
} 

#endif
